# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'document_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ocument_service.proto\x12\x08\x64ocument\"B\n\x1bUpdateDocumentStatusRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\")\n\x12GetDocumentRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\",\n\x15\x44ocumentExistsRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"\xc6\x01\n\x10\x44ocumentResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x12\n\ncreated_by\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x14\n\x0c\x63ontent_size\x18\x06 \x01(\x03\x12\x0e\n\x06s3_key\x18\x07 \x01(\t\x12\x12\n\ncreated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_at\x18\t \x01(\t\x12\x0f\n\x07version\x18\n \x01(\x05\"8\n\x16\x44ocumentExistsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t2\x8a\x02\n\x0f\x44ocumentService\x12Y\n\x14UpdateDocumentStatus\x12%.document.UpdateDocumentStatusRequest\x1a\x1a.document.DocumentResponse\x12G\n\x0bGetDocument\x12\x1c.document.GetDocumentRequest\x1a\x1a.document.DocumentResponse\x12S\n\x0e\x44ocumentExists\x12\x1f.document.DocumentExistsRequest\x1a .document.DocumentExistsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPDATEDOCUMENTSTATUSREQUEST']._serialized_start=36
  _globals['_UPDATEDOCUMENTSTATUSREQUEST']._serialized_end=102
  _globals['_GETDOCUMENTREQUEST']._serialized_start=104
  _globals['_GETDOCUMENTREQUEST']._serialized_end=145
  _globals['_DOCUMENTEXISTSREQUEST']._serialized_start=147
  _globals['_DOCUMENTEXISTSREQUEST']._serialized_end=191
  _globals['_DOCUMENTRESPONSE']._serialized_start=194
  _globals['_DOCUMENTRESPONSE']._serialized_end=392
  _globals['_DOCUMENTEXISTSRESPONSE']._serialized_start=394
  _globals['_DOCUMENTEXISTSRESPONSE']._serialized_end=450
  _globals['_DOCUMENTSERVICE']._serialized_start=453
  _globals['_DOCUMENTSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
