# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import document_service_pb2 as document__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in document_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """DocumentService handles document operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateDocumentStatus = channel.unary_unary(
                '/document.DocumentService/UpdateDocumentStatus',
                request_serializer=document__service__pb2.UpdateDocumentStatusRequest.SerializeToString,
                response_deserializer=document__service__pb2.DocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/document.DocumentService/GetDocument',
                request_serializer=document__service__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=document__service__pb2.DocumentResponse.FromString,
                _registered_method=True)
        self.DocumentExists = channel.unary_unary(
                '/document.DocumentService/DocumentExists',
                request_serializer=document__service__pb2.DocumentExistsRequest.SerializeToString,
                response_deserializer=document__service__pb2.DocumentExistsResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """DocumentService handles document operations.
    """

    def UpdateDocumentStatus(self, request, context):
        """Updates the status of a document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Retrieves a document by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DocumentExists(self, request, context):
        """Checks if a document exists.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateDocumentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDocumentStatus,
                    request_deserializer=document__service__pb2.UpdateDocumentStatusRequest.FromString,
                    response_serializer=document__service__pb2.DocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=document__service__pb2.GetDocumentRequest.FromString,
                    response_serializer=document__service__pb2.DocumentResponse.SerializeToString,
            ),
            'DocumentExists': grpc.unary_unary_rpc_method_handler(
                    servicer.DocumentExists,
                    request_deserializer=document__service__pb2.DocumentExistsRequest.FromString,
                    response_serializer=document__service__pb2.DocumentExistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """DocumentService handles document operations.
    """

    @staticmethod
    def UpdateDocumentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/UpdateDocumentStatus',
            document__service__pb2.UpdateDocumentStatusRequest.SerializeToString,
            document__service__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/GetDocument',
            document__service__pb2.GetDocumentRequest.SerializeToString,
            document__service__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DocumentExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/DocumentExists',
            document__service__pb2.DocumentExistsRequest.SerializeToString,
            document__service__pb2.DocumentExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
